//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mymusicpol.Views.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mymusicpol.Views.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        public static string addToPlaylist {
            get {
                return ResourceManager.GetString("addToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string addToQueue {
            get {
                return ResourceManager.GetString("addToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to instantly add to queue
        ///Right click to open additional context menu.
        /// </summary>
        public static string addToQueueToolTip {
            get {
                return ResourceManager.GetString("addToQueueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string album {
            get {
                return ResourceManager.GetString("album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Music.
        /// </summary>
        public static string allMusic {
            get {
                return ResourceManager.GetString("allMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string artist {
            get {
                return ResourceManager.GetString("artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name cannot be empty.
        /// </summary>
        public static string cmbCannotEmpty {
            get {
                return ResourceManager.GetString("cmbCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error.
        /// </summary>
        public static string cmbErrorExport {
            get {
                return ResourceManager.GetString("cmbErrorExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        public static string cmbErrorImport {
            get {
                return ResourceManager.GetString("cmbErrorImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Link.
        /// </summary>
        public static string cmbErrorInvLink {
            get {
                return ResourceManager.GetString("cmbErrorInvLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string cmbErrorInvName {
            get {
                return ResourceManager.GetString("cmbErrorInvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export playlist.
        /// </summary>
        public static string cmbExportFail {
            get {
                return ResourceManager.GetString("cmbExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import playlist.
        /// </summary>
        public static string cmbImportFail {
            get {
                return ResourceManager.GetString("cmbImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find song.
        /// </summary>
        public static string cmbInvLink {
            get {
                return ResourceManager.GetString("cmbInvLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song added to queue.
        /// </summary>
        public static string cmbSongAddedToQueue {
            get {
                return ResourceManager.GetString("cmbSongAddedToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string cmbSuccess {
            get {
                return ResourceManager.GetString("cmbSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit name.
        /// </summary>
        public static string editName {
            get {
                return ResourceManager.GetString("editName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to export
        ///Right click to open additional context menu.
        /// </summary>
        public static string exportToolTip {
            get {
                return ResourceManager.GetString("exportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter playlist name to add song.
        /// </summary>
        public static string ibvAddSong {
            get {
                return ResourceManager.GetString("ibvAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new playlist name.
        /// </summary>
        public static string ibvPlaylistName {
            get {
                return ResourceManager.GetString("ibvPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string library {
            get {
                return ResourceManager.GetString("library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize To Tray.
        /// </summary>
        public static string minimizeToTray {
            get {
                return ResourceManager.GetString("minimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Queue.
        /// </summary>
        public static string openQueue {
            get {
                return ResourceManager.GetString("openQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Visualizer.
        /// </summary>
        public static string openVisualizer {
            get {
                return ResourceManager.GetString("openVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste an URL to your favourite Youtube song and play it on MyMusicPoL.
        /// </summary>
        public static string pasteUrl {
            get {
                return ResourceManager.GetString("pasteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Youtube link....
        /// </summary>
        public static string pasteYTLink {
            get {
                return ResourceManager.GetString("pasteYTLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play from web:.
        /// </summary>
        public static string playFromWeb {
            get {
                return ResourceManager.GetString("playFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string playlists {
            get {
                return ResourceManager.GetString("playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to open playlist
        ///Right click to open additional context menu.
        /// </summary>
        public static string playlistsToolTip {
            get {
                return ResourceManager.GetString("playlistsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string playPause {
            get {
                return ResourceManager.GetString("playPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string queue {
            get {
                return ResourceManager.GetString("queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Visualizer.
        /// </summary>
        public static string showVisualizer {
            get {
                return ResourceManager.GetString("showVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        public static string showWindow {
            get {
                return ResourceManager.GetString("showWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string sortBy {
            get {
                return ResourceManager.GetString("sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string welcomeTo {
            get {
                return ResourceManager.GetString("welcomeTo", resourceCulture);
            }
        }
    }
}
